### PR TITLE
remove stdlib dependency

### PR DESCRIPTION
**Pull request by poke1024**
cassowary.lua currently depends on a very old version of stdlib that is probably no longer supported (and is quite big as well). Newer versions of stdlib don't work at all due to various redesigns in stdlib.

This PR removes all stdlib dependencies by implementing `Object`, `Set`, `merge` and `clone` such that cassowary.lua is small and completely self-contained. This actually simplifies some of the existing `_init` code.

Tested under Lua 5.3 and LuaJIT.

All tests work (tested with Lua 5.3):

$ busted cassowary.lua/tests/
●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
73 successes / 0 failures / 0 errors / 0 pending : 0.091388 seconds

### CODE REVIEW

**Comment by tst2005** [comment]
There is a License issue : [std](https://github.com/lua-stdlib/lua-stdlib) is release under a different [LICENSE](https://github.com/lua-stdlib/lua-stdlib/blob/master/LICENSE.md) than [cassowary.lua](https://github.com/simoncozens/cassowary.lua#licence).

You should copy some [std](https://github.com/lua-stdlib/lua-stdlib) files outside of [cassowary.lua/cassowary.lua](https://github.com/simoncozens/cassowary.lua/blob/master/cassowary.lua) module.

If you need only one cassowary.lua file without std dependency, you should built it at a second step.
if is not too hard to inject the std modules in package.loaded.

Regards,

**Comment by poke1024** [comment]
Maybe I should explain some more why this makes sense to me. Apart from the current cassowary.lua not working with any recent stdlib, which is downright frustrating for anyone trying to use this, I find the size a problem in certain use cases, as cassowary only uses a super tiny part of stdlib. For local installations, this is not an issue at all. But if you need to go for small build sizes and ship your lua code via the Web, e.g. via Emscripten (e.g. https://github.com/TannerRogalsky/love.js/), then having a big lib dependency that basically does nothing but provide an Object wrapper, is not great. I'm using cassowary as part of a love2d project and most people from that world won't use luarocks or the like. In many cases, even having one additional lib file is considered bloat in that world. Now, as cassowary has no inherent dependency on stdlib, I really think that a self-contained cassowary would make many people quite happy.

**Comment by simoncozens** [comment]
Thanks so much for this patch. I think removing std and having a self-contained cassowary is a great idea. I wrote cassowary when I was fairly new to the Lua ecosystem and thought that stdlib (1) was the Lua standard library and (2) had a fairly mature attitude towards API compatibility, but neither of these is true. I'll review the PR soon but am busy with a house move right now.

**Comment by simoncozens** [comment]
Man, I'm sorry. I totally forgot all about this patch. It was a great idea, but we've gone in the direction of replacing std with penlight. I'm sort of wary of reimplementing core stuff like object inheritance from scratch, so I'm a bit happier with the penlight solution, but I'm sorry you put work into this and I completely dropped the ball.

**Comment by poke1024** [comment]
@simoncozens Hey, no problem, penlight is a good choice for sure.

**Pull request closed without merging**
